### ISSUE TITLE
Arya throws an "ImportError" exception on Windows

### ISSUE THREAD

**Issue by luismartingarcia** [datacenter/arya#1]
Hi,

Arya setup does not seem to work fine on Windows. After running python setup.py install, arya throws an ImportError exception when run. 

```
C:\code\arya>python -V
Python 2.7.9

C:\code\arya>python setup.py install
running install
running bdist_egg
running egg_info
writing arya.egg-info\PKG-INFO
writing top-level names to arya.egg-info\top_level.txt
writing dependency_links to arya.egg-info\dependency_links.txt
writing entry points to arya.egg-info\entry_points.txt
reading manifest file 'arya.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'arya.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
copying arya\arya.py -> build\lib\arya
creating build\bdist.win32\egg
creating build\bdist.win32\egg\arya
copying build\lib\arya\apicxmljson.py -> build\bdist.win32\egg\arya
copying build\lib\arya\arya.py -> build\bdist.win32\egg\arya
copying build\lib\arya\getconfigfromapic.py -> build\bdist.win32\egg\arya
copying build\lib\arya\version.py -> build\bdist.win32\egg\arya
copying build\lib\arya\__init__.py -> build\bdist.win32\egg\arya
byte-compiling build\bdist.win32\egg\arya\apicxmljson.py to apicxmljson.pyc
byte-compiling build\bdist.win32\egg\arya\arya.py to arya.pyc
byte-compiling build\bdist.win32\egg\arya\getconfigfromapic.py to getconfigfromapic.pyc
byte-compiling build\bdist.win32\egg\arya\version.py to version.pyc
byte-compiling build\bdist.win32\egg\arya\__init__.py to __init__.pyc
creating build\bdist.win32\egg\EGG-INFO
installing scripts to build\bdist.win32\egg\EGG-INFO\scripts
running install_scripts
running build_scripts
copying and adjusting arya\arya.py -> build\scripts-2.7
creating build\bdist.win32\egg\EGG-INFO\scripts
copying build\scripts-2.7\apicxmljson.py -> build\bdist.win32\egg\EGG-INFO\scripts
copying build\scripts-2.7\arya.py -> build\bdist.win32\egg\EGG-INFO\scripts
copying build\scripts-2.7\getconfigfromapic.py -> build\bdist.win32\egg\EGG-INFO\scripts
copying build\scripts-2.7\version.py -> build\bdist.win32\egg\EGG-INFO\scripts
copying arya.egg-info\PKG-INFO -> build\bdist.win32\egg\EGG-INFO
copying arya.egg-info\SOURCES.txt -> build\bdist.win32\egg\EGG-INFO
copying arya.egg-info\dependency_links.txt -> build\bdist.win32\egg\EGG-INFO
copying arya.egg-info\entry_points.txt -> build\bdist.win32\egg\EGG-INFO
copying arya.egg-info\not-zip-safe -> build\bdist.win32\egg\EGG-INFO
copying arya.egg-info\top_level.txt -> build\bdist.win32\egg\EGG-INFO
creating 'dist\arya-1.1.3-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing arya-1.1.3-py2.7.egg
removing 'c:\python27\lib\site-packages\arya-1.1.3-py2.7.egg' (and everything under it)
creating c:\python27\lib\site-packages\arya-1.1.3-py2.7.egg
Extracting arya-1.1.3-py2.7.egg to c:\python27\lib\site-packages
arya 1.1.3 is already the active version in easy-install.pth
Installing apicxmljson.py script to C:\Python27\Scripts
Installing arya.py script to C:\Python27\Scripts
Installing getconfigfromapic.py script to C:\Python27\Scripts
Installing version.py script to C:\Python27\Scripts
Deleting C:\Python27\Scripts\getconfigfromapic.py
Installing getconfigfromapic-script.py script to C:\Python27\Scripts
Installing getconfigfromapic.exe script to C:\Python27\Scripts
Installing getconfigfromapic.exe.manifest script to C:\Python27\Scripts
Deleting C:\Python27\Scripts\arya.py
Installing arya-script.py script to C:\Python27\Scripts
Installing arya.exe script to C:\Python27\Scripts
Installing arya.exe.manifest script to C:\Python27\Scripts
Deleting C:\Python27\Scripts\apicxmljson.py
Installing apicxmljson-script.py script to C:\Python27\Scripts
Installing apicxmljson.exe script to C:\Python27\Scripts
Installing apicxmljson.exe.manifest script to C:\Python27\Scripts

Installed c:\python27\lib\site-packages\arya-1.1.3-py2.7.egg
Processing dependencies for arya==1.1.3
Finished processing dependencies for arya==1.1.3

C:\code\arya>arya
Traceback (most recent call last):
  File "C:\Python27\Scripts\arya-script.py", line 9, in <module>
    load_entry_point('arya==1.1.3', 'console_scripts', 'arya')()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 339, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2470, in load_entry_point
    return ep.load()
  File "C:\Python27\lib\site-packages\pkg_resources.py", line 2189, in load
    raise ImportError("%r has no %r attribute" % (entry, attr))
ImportError: <module 'arya' from 'C:\Python27\lib\site-packages\arya-1.1.3-py2.7.egg\arya\__init__.pyc'> has no 'main' attribute
```

The problem does not show up when run under cygwin:

```
lumarti2@LUMARTI2-WS03 ~/repos/arya
$ python -V
Python 2.7.8

lumarti2@LUMARTI2-WS03 ~/repos/arya
$ python setup.py install
running install
running bdist_egg
running egg_info
writing arya.egg-info/PKG-INFO
writing top-level names to arya.egg-info/top_level.txt
writing dependency_links to arya.egg-info/dependency_links.txt
writing entry points to arya.egg-info/entry_points.txt
reading manifest file 'arya.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'arya.egg-info/SOURCES.txt'
installing library code to build/bdist.cygwin-1.7.35-x86_64/egg
running install_lib
running build_py
copying arya/arya.py -> build/lib/arya
creating build/bdist.cygwin-1.7.35-x86_64/egg
creating build/bdist.cygwin-1.7.35-x86_64/egg/arya
copying build/lib/arya/apicxmljson.py -> build/bdist.cygwin-1.7.35-x86_64/egg/arya
copying build/lib/arya/arya.py -> build/bdist.cygwin-1.7.35-x86_64/egg/arya
copying build/lib/arya/getconfigfromapic.py -> build/bdist.cygwin-1.7.35-x86_64/egg/arya
copying build/lib/arya/version.py -> build/bdist.cygwin-1.7.35-x86_64/egg/arya
copying build/lib/arya/__init__.py -> build/bdist.cygwin-1.7.35-x86_64/egg/arya
byte-compiling build/bdist.cygwin-1.7.35-x86_64/egg/arya/apicxmljson.py to apicxmljson.pyc
byte-compiling build/bdist.cygwin-1.7.35-x86_64/egg/arya/arya.py to arya.pyc
byte-compiling build/bdist.cygwin-1.7.35-x86_64/egg/arya/getconfigfromapic.py to getconfigfromapic.pyc
byte-compiling build/bdist.cygwin-1.7.35-x86_64/egg/arya/version.py to version.pyc
byte-compiling build/bdist.cygwin-1.7.35-x86_64/egg/arya/__init__.py to __init__.pyc
creating build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
installing scripts to build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
copying and adjusting arya/arya.py -> build/scripts-2.7
creating build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/apicxmljson.py -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/arya.py -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/getconfigfromapic.py -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts/apicxmljson.py to 755
changing mode of build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts/arya.py to 755
changing mode of build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO/scripts/getconfigfromapic.py to 755
copying arya.egg-info/PKG-INFO -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
copying arya.egg-info/SOURCES.txt -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
copying arya.egg-info/dependency_links.txt -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
copying arya.egg-info/entry_points.txt -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
copying arya.egg-info/not-zip-safe -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
copying arya.egg-info/top_level.txt -> build/bdist.cygwin-1.7.35-x86_64/egg/EGG-INFO
creating 'dist/arya-1.1.3-py2.7.egg' and adding 'build/bdist.cygwin-1.7.35-x86_64/egg' to it
removing 'build/bdist.cygwin-1.7.35-x86_64/egg' (and everything under it)
Processing arya-1.1.3-py2.7.egg
removing '/usr/lib/python2.7/site-packages/arya-1.1.3-py2.7.egg' (and everything under it)
creating /usr/lib/python2.7/site-packages/arya-1.1.3-py2.7.egg
Extracting arya-1.1.3-py2.7.egg to /usr/lib/python2.7/site-packages
arya 1.1.3 is already the active version in easy-install.pth
Installing apicxmljson.py script to /usr/bin
Installing arya.py script to /usr/bin
Installing getconfigfromapic.py script to /usr/bin
Installing getconfigfromapic script to /usr/bin
Installing arya script to /usr/bin
Installing apicxmljson script to /usr/bin

Installed /usr/lib/python2.7/site-packages/arya-1.1.3-py2.7.egg
Processing dependencies for arya==1.1.3
Finished processing dependencies for arya==1.1.3

lumarti2@LUMARTI2-WS03 ~/repos/arya
$ arya
ERROR: You must specify at least -d, -f, or -s

usage: Code generator for APIC cobra SDK [-h] [-f FILEIN] [-s] [-d SOURCEDIR]
                                         [-t TARGETDIR] [-i IP] [-u USERNAME]
                                         [-p PASSWORD] [-nc]

optional arguments:
  -h, --help            show this help message and exit
  -f FILEIN, --filein FILEIN
                        Document containing post to be sent to REST API
  -s, --stdin           Parse input from stdin, for use as a filter, e.g., cat
                        doc.xml | arya -s
  -d SOURCEDIR, --sourcedir SOURCEDIR
                        Specify a source directory containing ACI object files
                        you want to convert to python.
  -t TARGETDIR, --targetdir TARGETDIR
                        Where to write the .py files that come from the -d
                        directory. If none is specified, it will default to
                        SOURCEDIR
  -i IP, --ip IP        IP address of APIC to be pre-populated
  -u USERNAME, --username USERNAME
                        Username for APIC account to be pre-populated in
                        generated code
  -p PASSWORD, --password PASSWORD
                        Password for APIC account to be pre-populated in
                        generated code
  -nc, --nocommit       Generate code without final commit to changes

lumarti2@LUMARTI2-WS03 ~/repos/arya
$ whereis arya
arya: /usr/bin/arya /usr/bin/arya.py /usr/bin/arya.pyc /cygdrive/c/Python27/Scripts/arya.exe /cygdrive/c/Python27/Scripts/arya.py

lumarti2@LUMARTI2-WS03 ~/repos/arya
```

In addition, Arya runs just fine when executing python /arya/arya.py, so this seems to be some kind of error caused by the setup.py file.

```
C:\code\arya\arya>python arya.py
ERROR: You must specify at least -d, -f, or -s

usage: Code generator for APIC cobra SDK [-h] [-f FILEIN] [-s] [-d SOURCEDIR]
                                         [-t TARGETDIR] [-i IP] [-u USERNAME]
                                         [-p PASSWORD] [-nc]

optional arguments:
  -h, --help            show this help message and exit
  -f FILEIN, --filein FILEIN
                        Document containing post to be sent to REST API
  -s, --stdin           Parse input from stdin, for use as a filter, e.g., cat
                        doc.xml | arya.py -s
  -d SOURCEDIR, --sourcedir SOURCEDIR
                        Specify a source directory containing ACI object files
                        you want to convert to python.
  -t TARGETDIR, --targetdir TARGETDIR
                        Where to write the .py files that come from the -d
                        directory. If none is specified, it will default to
                        SOURCEDIR
  -i IP, --ip IP        IP address of APIC to be pre-populated
  -u USERNAME, --username USERNAME
                        Username for APIC account to be pre-populated in
                        generated code
  -p PASSWORD, --password PASSWORD
                        Password for APIC account to be pre-populated in
                        generated code
  -nc, --nocommit       Generate code without final commit to changes
```

This is on a regular Windows 7 laptop. Could you please have a look into the issue? 

Thanks a lot. Best regards,

Luis.

**Comment by mtimm** [comment]
Hi Luis,

Arya is on pypi now, you might want to try:

```
pip install arya
```

I don't have a windows box to easily test with but let me look into this and get back to you.

Mike
