### ISSUE TITLE
Can Arya run on Python3.7

### ISSUE THREAD

**Issue by jrleriche** [datacenter/arya#14]
I am having the the error below when trying to run it 

C:\>arya -f /Users/leje6024/Downloads/BD-Hero_Land.json
Traceback (most recent call last):
  File "C:\Users\leje6024\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2419, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'arya' has no attribute 'main'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\leje6024\AppData\Local\Programs\Python\Python37\Scripts\arya-script.py", line 11, in <module>
    load_entry_point('arya==1.1.5', 'console_scripts', 'arya')()
  File "C:\Users\leje6024\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\leje6024\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "C:\Users\leje6024\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "C:\Users\leje6024\AppData\Local\Programs\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: module 'arya' has no attribute 'main'

Thanks for your help

**Comment by atarlov** [comment]
I faced the same when running into a venv. You can use the araya.py directly from package.

**Comment by andyitsus** [comment]
I'm getting exactly the same problem as https://github.com/datacenter/arya/issues/14#issue-721099028
