### ISSUE TITLE
Admin implicit props cannot be modified, class=fvBD, prop=bcastP

### ISSUE THREAD

**Issue by NathanDotTo** [datacenter/arya#8]
cisco@cisco:~/Downloads$ python arya_tenant_json_discovery.py 
/home/cisco/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
<?xml version="1.0" encoding="UTF-8"?>
<polUni status='created,modified'><fvTenant ownerKey='' name='Cobra_Tenant_2' descr='' status='created,modified' ownerTag=''><fvBD status='created,modified' multiDstPktAct='bd-flood' seg='16252846' unicastRoute='yes' unkMcastAct='flood' descr='' llAddr='::' vmac='not-applicable' bcastP='225.1.94.192' mac='00:22:BD:F8:19:FF' epMoveDetectMode='' ownerTag='' ownerKey='' name='bd2' unkMacUcastAct='proxy' arpFlood='no' limitIpLearnToSubnets='no' mtu='inherit' pcTag='32770'><fvRsBdToEpRet tRn='epRPol-default' tDn='uni/tn-common/epRPol-default' rType='mo' tContextDn='' resolveAct='resolve' forceResolve='yes' status='created,modified' tCl='fvEpRetPol' tType='name' tnFvEpRetPolName=''></fvRsBdToEpRet><fvRsBDToNdP tRn='ndifpol-default' tDn='uni/tn-common/ndifpol-default' rType='mo' tCl='ndIfPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name' tnNdIfPolName=''></fvRsBDToNdP><fvRsCtx tRn='ctx-pvn2' tDn='uni/tn-Cobra_Tenant_2/ctx-pvn2' rType='mo' tCl='fvCtx' tContextDn='' forceResolve='yes' status='created,modified' tType='name' tnFvCtxName='pvn2'></fvRsCtx><fvRsIgmpsn tRn='snPol-default' tDn='uni/tn-common/snPol-default' rType='mo' tnIgmpSnoopPolName='' tCl='igmpSnoopPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name'></fvRsIgmpsn></fvBD><fvRsTenantMonPol tRn='monepg-default' tDn='uni/tn-common/monepg-default' rType='mo' tCl='monEPGPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name' tnMonEPGPolName=''></fvRsTenantMonPol><fvCtx ownerKey='' name='pvn2' descr='' knwMcastAct='permit' seg='3112960' pcEnfDir='ingress' pcTag='16386' pcEnfDirUpdated='yes' status='created,modified' ownerTag='' pcEnfPref='enforced'><fvRsCtxToEpRet tRn='epRPol-default' tDn='uni/tn-common/epRPol-default' rType='mo' tCl='fvEpRetPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name' tnFvEpRetPolName=''></fvRsCtxToEpRet><fvRsCtxToExtRouteTagPol tRn='rttag-default' tDn='uni/tn-common/rttag-default' rType='mo' tCl='l3extRouteTagPol' tContextDn='' forceResolve='yes' status='created,modified' tnL3extRouteTagPolName='' tType='name'></fvRsCtxToExtRouteTagPol><vzAny matchT='AtleastOne' name='' descr='' pcTag='any' status='created,modified' useAnyDef='yes'></vzAny><fvRsOspfCtxPol tRn='ospfCtxP-default' tDn='uni/tn-common/ospfCtxP-default' rType='mo' tCl='ospfCtxPol' tnOspfCtxPolName='' tContextDn='' forceResolve='yes' status='created,modified' tType='name'></fvRsOspfCtxPol><fvRsBgpCtxPol tRn='bgpCtxP-default' tDn='uni/tn-common/bgpCtxP-default' rType='mo' tnBgpCtxPolName='' tCl='bgpCtxPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name'></fvRsBgpCtxPol></fvCtx><fvAp ownerKey='' name='OnlineStore2' descr='' status='created,modified' ownerTag='' prio='unspecified'><fvAEPg isAttrBasedEPg='no' matchT='AtleastOne' name='web2' descr='' txId='767' pcTag='32772' status='created,modified' prio='unspecified' pcEnfPref='unenforced'><fvRsCustQosPol tRn='qoscustom-default' tDn='uni/tn-common/qoscustom-default' tnQosCustomPolName='' rType='mo' tCl='qosCustomPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name'></fvRsCustQosPol><fvRsBd tRn='BD-bd2' tDn='uni/tn-Cobra_Tenant_2/BD-bd2' rType='mo' tCl='fvBD' tContextDn='' forceResolve='yes' status='created,modified' tnFvBDName='bd2' tType='name'><fvSubnetBDDefCont name='' bddefDn='uni/bd-[uni/tn-Cobra_Tenant_2/BD-bd2]-isSvc-no' status='created,modified'></fvSubnetBDDefCont></fvRsBd></fvAEPg><fvAEPg isAttrBasedEPg='no' matchT='AtleastOne' name='db2' descr='' txId='767' pcTag='32771' status='created,modified' prio='unspecified' pcEnfPref='unenforced'><fvRsCustQosPol tRn='qoscustom-default' tDn='uni/tn-common/qoscustom-default' tnQosCustomPolName='' rType='mo' tCl='qosCustomPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name'></fvRsCustQosPol><fvRsBd tRn='BD-bd2' tDn='uni/tn-Cobra_Tenant_2/BD-bd2' rType='mo' tCl='fvBD' tContextDn='' forceResolve='yes' status='created,modified' tnFvBDName='bd2' tType='name'><fvSubnetBDDefCont name='' bddefDn='uni/bd-[uni/tn-Cobra_Tenant_2/BD-bd2]-isSvc-no' status='created,modified'></fvSubnetBDDefCont></fvRsBd></fvAEPg><fvAEPg isAttrBasedEPg='no' matchT='AtleastOne' name='app2' descr='' txId='767' pcTag='49153' status='created,modified' prio='unspecified' pcEnfPref='unenforced'><fvRsCustQosPol tRn='qoscustom-default' tDn='uni/tn-common/qoscustom-default' tnQosCustomPolName='' rType='mo' tCl='qosCustomPol' tContextDn='' forceResolve='yes' status='created,modified' tType='name'></fvRsCustQosPol><fvRsBd tRn='BD-bd2' tDn='uni/tn-Cobra_Tenant_2/BD-bd2' rType='mo' tCl='fvBD' tContextDn='' forceResolve='yes' status='created,modified' tnFvBDName='bd2' tType='name'><fvSubnetBDDefCont name='' bddefDn='uni/bd-[uni/tn-Cobra_Tenant_2/BD-bd2]-isSvc-no' status='created,modified'></fvSubnetBDDefCont></fvRsBd></fvAEPg></fvAp></fvTenant></polUni>
/home/cisco/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "arya_tenant_json_discovery.py", line 53, in <module>
    md.commit(c)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_2i-py2.7.egg/cobra/mit/access.py", line 58, in commit
    return self._accessImpl.post(configObject)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_2i-py2.7.egg/cobra/internal/rest/accessimpl.py", line 175, in post
    return self.__parseError(rsp, CommitError, rsp.status_code)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_2i-py2.7.egg/cobra/internal/rest/accessimpl.py", line 181, in __parseError
    parseXMLError(rsp.text, errorClass, httpCode)
  File "/usr/local/lib/python2.7/dist-packages/acicobra-1.3_2i-py2.7.egg/cobra/mit/xmlcodec.py", line 15, in parseXMLError
    raise errorClass(int(errorCode), errorStr, httpCode)
cobra.mit.request.CommitError: Admin implicit props cannot be modified, class=fvBD, prop=bcastP
cisco@cisco:~/Downloads$

**Comment by NathanDotTo** [comment]
Code and JSON document attached.

[Archive.zip](https://github.com/datacenter/arya/files/496629/Archive.zip)

**Comment by lmalhoit** [comment]
Did you ever figure this out?

**Comment by glennake** [comment]
Is this not expected behaviour?
You are trying to set the bcastP value of an fvBD (Bridge Domain) object, which is an implicit parameter.

This is the line below from your Python code:

`fvBD = cobra.model.fv.BD(fvTenant, multiDstPktAct=u'bd-flood', seg=u'16252846', unicastRoute=u'yes', unkMcastAct=u'flood', descr=u'', llAddr=u'::', vmac=u'not-applicable', bcastP=u'225.1.94.192', mac=u'00:22:BD:F8:19:FF', epMoveDetectMode=u'', ownerTag=u'', ownerKey=u'', name=u'bd2', unkMacUcastAct=u'proxy', arpFlood=u'no', limitIpLearnToSubnets=u'no', mtu=u'inherit', pcTag=u'32770')`

This is the Cisco APIC Model Reference definition for bcastP of fvBD:

```
bcastP

Type: mcast:Group
Primitive Type: address:IPv4

Units: null
Encrypted: false
Access: implicit
Category: TopLevelRegular
Comments:
Outer multicast group IP address.
```

As an implicit parameter it is inherited from another object, in this case fvL2Dom.

When I have created fvBD objects I did not provide a bcastP parameter and it allocated a multicast IP address from the pool configured on my APIC.
